spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/food
    username: root
    password: 1234
  jpa:
    show-sql: true  #실행하는 쿼리 보이게
    properties:
      hibernate:
        format_sql: true  #쿼리 가독성
    hibernate:
      ddl-auto: none   #프로젝트 실행할때마다 생성-삭제
    defer-datasource-initialization : true  #data.sql 실행 여부
    generate-ddl : true  #Entity에서 활용하는 테이블 자동 생성 여부

logging:
  level:
    root: info