spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/food_preference
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate :
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  security:
    user:
      name: user1
      password: 1234
      roles: USER
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/data.sql
#logging:
#  level:
#    root: info