spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/food_preference
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate :
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    generate-ddl: true
  security:
    user:
      name: user1
      password: 1234
      roles: USER
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
#logging:
#  level:
#    root: info